import type { CommandHistoryItem, Reminder } from "@/types/reminder";
import { formatShortDateTime } from "@/lib/time";

export default function ReminderList({ reminders, history, onDelete, onClearHistory }: { reminders: Reminder[]; history: CommandHistoryItem[]; onDelete: (id: string) => void; onClearHistory: () => void }) {
  return <section className="card" aria-labelledby="reminder-title"><h2 id="reminder-title" className="text-2xl font-bold text-[var(--text)]">Reminder & Riwayat</h2>
    <div className="mt-4"><p className="font-semibold text-[var(--text)]">Reminder aktif</p>{reminders.length === 0 ? <p className="mt-2 break-words text-sm text-[var(--text-soft)]">Belum ada reminder. Coba: “ingatkan aku jam 7 malam”.</p> : <div className="mt-2 grid gap-2">{reminders.map((r) => <div key={r.id} className="grid gap-3 rounded-2xl border border-[var(--border)] bg-[var(--bg-soft)] p-3 sm:grid-cols-[1fr_auto] sm:items-center"><div className="min-w-0"><p className="break-words font-medium text-[var(--text)]">{r.label}</p><p className="text-sm text-[var(--text-soft)]">{formatShortDateTime(new Date(r.scheduledAt))}</p></div><button className="btn-secondary" onClick={() => onDelete(r.id)} aria-label={`Hapus ${r.label}`}>Hapus</button></div>)}</div>}</div>
    <div className="mt-6"><div className="grid gap-2 sm:flex sm:items-center sm:justify-between"><p className="font-semibold text-[var(--text)]">10 perintah terakhir</p><button className="btn-secondary" onClick={onClearHistory}>Bersihkan</button></div>{history.length === 0 ? <p className="mt-2 break-words text-sm text-[var(--text-soft)]">Riwayat perintah tersimpan privat di perangkat ini.</p> : <ol className="mt-2 grid gap-2">{history.map((h) => <li key={h.id} className="rounded-2xl border border-[var(--border)] bg-[var(--bg-soft)] p-3 text-sm"><p className="break-words font-semibold text-[var(--text)]">“{h.command}”</p><p className="break-words text-[var(--text-soft)]">{h.response}</p><time className="text-xs text-[var(--muted)]">{formatShortDateTime(new Date(h.createdAt))}</time></li>)}</ol>}</div>
  </section>;
}
